### ISSUE TITLE
Crash with Design Pattern

### ISSUE THREAD

**Issue by Remyrios** [codetaylor/artisan-worktables#107]
#### Intro

Please follow the template when submitting an issue.

If you are submitting a suggestion, feature request, or idea, please delete this template and follow the guidelines found in the README.md file.

If you do not follow the template or guidelines, your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

Minecraft crashes when shift clicking design pattern into designer's worktable.

#### What Happens

Minecraft crashes in a situation described above.
Steps to reproduce:
- Place Designer's Worktable
- Shift click design pattern into Designer's Worktable while in it's GUI

#### What You Expect to Happen

Nothing. I haven't created any recipe in this table yet

#### Script

No scripts involved

#### Crash Log

https://hastebin.com/acocuqukiz.sql

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.2.2654
* CraftTweaker: 4.1.6
* Artisan Worktables: 1.19.0-SNAPSHOT.1
* Athenaeum: 1.14.0

**Comment by codetaylor** [comment]
Thanks for reporting this! :)

This issue exposed two issues. First, any table without the pattern slots would crash on shift click due to a -1 array index. Second, the code used to search for adjacent designer tables was incorrect, which caused stand-alone designer tables to not have the pattern slots.

Regarding operation:

1. Place the designer's table adjacent to other tables (like the toolbox). 
2. Open one of the other tables. 
3. Observe the pattern slot gui. 
4. Place blank patterns where indicated. 
5. Complete valid recipe in a table. 
6. Observe the pattern result slot is populated. 
7. Take written pattern from pattern result slot.

There are other ways to use the patterns. You can create your own written pattern by attaching the recipe name via NBT. You can create recipes that require specific patterns. Patterns are a precursor to automation, but can be used in other ways.

The alpha doc changes aren't live yet, but you can read about recipe names here: https://github.com/codetaylor/artisan-worktables/blob/release/next/docs/recipes/names.md

I'll have documentation on this when this version is released as beta. It is available as alpha snapshots right now, which means things might change and there are probably bugs.

**Comment by codetaylor** [comment]
Oh, the Designer's Table functions as both a regular table and as a block that gives additional functionality to adjacent tables, similar to the toolbox.

**Comment by codetaylor** [comment]
Fixed in 1.12.2-1.19.0-SNAPSHOT.2
