### ISSUE TITLE
Add a configuration option to disable registration individual types of worktables

### ISSUE THREAD

**Issue by mallrat208** [codetaylor/artisan-worktables#112]
This kind of goes hand in hand with the ability to disable certain types of tools, but it would be useful to be able to disable individual worktable types from registering all together. It wasn't so bad when the mod first released and there were only five worktables with no tiering but as it sits now there are about 45 different type of work(blanks) added contributing to clutter and a bit of confusion as to why certain blocks may have recipes and others don't as well as to if they're needed or not.

**Comment by codetaylor** [comment]
I've implemented a solution to your problem. Because of the way tables are registered and managed, preventing table types from being registered presents many difficulties and the result does not justify the amount of work required. Instead the disabled table types are simply removed from JEI when the JEI runtime becomes available. Just as if you made three calls to `mods.jei.JEI.hide(<tablehere>);` in your ZenScript, one for the type in each tier.

I hope this helps solve your problem! :) It will be available in the next alpha.

**Comment by codetaylor** [comment]
This feature is available in 1.12.2-1.19.0-SNAPSHOT.5
