### ISSUE TITLE
Designer worktable documentation

### ISSUE THREAD

**Issue by Rosethorns** [codetaylor/artisan-worktables#118]
From the the apparent integration in game it appears that when a table is next to a designer table it allows that table (for example a carpenter) to receive a blueprint. My assumption is that this blueprint is a further requirement to a craft. For example you may know the recipe for a wheel from Animania but you can't craft it unless you have a "wheel" design in the design slot.
Is this correct?
I couldn't find any documentation for the design table in the changelog or on the site so I'm flying blind here.
Perhaps the design table is unfinished and its part of the intended automation stuff?

**Comment by codetaylor** [comment]
Right now, when the design pattern slot comes up next to a table, you lay out a valid recipe in the table, then you put a blank pattern into it and take out a written pattern. The written pattern contains NBT data with the name of the recipe. The written recipe can be used as a recipe ingredient in another recipe. You could also add other ways for players to get those written recipes if you wanted; ie. loot tables, quest rewards.

You are correct, the patterns are a step toward the intended automation stuff, but they can still be useful in their current form.

I'll add documentation when the feature leaves alpha, because things may yet change.

Hope that helps. :)
