### ISSUE TITLE
Astral Sorcery Crafting Detection

### ISSUE THREAD

**Issue by Vyraal1** [codetaylor/artisan-worktables#145]
#### Issue Description

Astral Sorcery has an internal progression that's usually unlocked by crafting key altar blocks within the mod. It has adjusted it's detection method to detect 3x3 recipes if Pack Dev's want to change it, however it doesn't seem to be detected when crafting in an Artisan Worktable.

#### What Happens

Given this recipe it should give the player the BASIC_CRAFT progression.
![image](https://user-images.githubusercontent.com/26587049/50530995-92de5e00-0ad1-11e9-9f8c-d43676218dc7.png)

This is given by: `/astralsorcery progress`
![image](https://user-images.githubusercontent.com/26587049/50530998-a4276a80-0ad1-11e9-8a95-9d876ef8cc7c.png)

#### What You Expect to Happen

I expect it to have BASIC_CRAFT unlocked once the Luminous Crafting Table is crafted and pulled from the Artisan Worktable.
![image](https://user-images.githubusercontent.com/26587049/50531007-c8834700-0ad1-11e9-8682-aa64d4bf617b.png)

#### Script

https://gist.github.com/Vyraal1/28e16f265c27eb9c1554990b55ecb063

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2781
* CraftTweaker: 4.1.13
* Artisan Worktables: 1.19.5
* Athenaeum: 1.15.0

**Comment by codetaylor** [comment]
Looks like AS listens for the `ItemCraftedEvent` which AW doesn't fire.

https://github.com/HellFirePvP/AstralSorcery/blob/ab2c9c9c54deb2313bed44bf5cf25d7ff37e9b3b/src/main/java/hellfirepvp/astralsorcery/common/event/listener/EventHandlerServer.java#L211

I remember looking into the event before, but I don't really remember the details of why I chose to implement a custom event instead of firing the Forge event - pretty sure I couldn't satisfy the field requirements of the event.

I'll look into this more tomorrow.

**Comment by codetaylor** [comment]
@Vyraal1 also, if you're interested, I started a discord for my mods: discord.gg/HY69E8X

**Comment by codetaylor** [comment]
Fixed in 1.12.2-1.20.0
