### ISSUE TITLE
Copying mod recipes to table doesn't work on servers

### ISSUE THREAD

**Issue by Konclan** [codetaylor/artisan-worktables#154]
I've copied all the recipes from IronChests to the Engineers worktable which works on singleplayer, but on a server, some recipes don't work even though they show like they should.

I have the exact same mods, scripts, and configs on both the server and client. The only mods I have are the required ones + Iron Chests [7.0.59.842] & JEI [4.14.4.264]

https://pastebin.com/zUAzDzAD

https://youtu.be/jsRAEKiNWDM

* Minecraft: 1.12.2
* Forge: 14.23.5.2784
* CraftTweaker: 4.1.14
* Artisan Worktables: 1.20.1
* Athenaeum: 1.16.0

**Comment by codetaylor** [comment]
I was able to reproduce the issue using:
* Minecraft: 1.12.2
* Forge: 14.23.5.2784
* CraftTweaker: 4.1.14
* Artisan Worktables: 1.20.1
* Athenaeum: 1.16.0
* Iron Chests: 7.0.59.842
* JEI: 4.14.4.264

The issue only appears using a dedicated server. It does not occur in single-player or when a single-player game is opened to LAN.

**Comment by codetaylor** [comment]
I have done some research into this problem and I have concluded that the solution to this issue lies outside the domain of AW.

The item and subsequent recipe iteration in the CrT script yields results on a dedicated server that are significantly different than those returned on a client.

I used an altered version of the provided script to print all the recipes resource names and launched both the server and client to log the results. The client logged 206 recipes while the server logged only 52.

```js
for i in loadedMods["ironchest"].items {
  for recipe in recipes.getRecipesFor(i){
    print(recipe.fullResourceDomain);
  }
}
```

The results can be seen here: https://gist.github.com/codetaylor/ef43363070b0c0feabc97fd517faab92
