### ISSUE TITLE
Tools Not Respecting Rename Script

### ISSUE THREAD

**Issue by Boolyman** [codetaylor/artisan-worktables#178]
#### Issue Description

Renaming tools in Crafttweaker causes them all to be named the same thing.

#### What Happens

I need a Soldering Iron tool for the Engineers Table.  Your Punches are the closest looking tools, so I used CT to rename each Punch Type - See script link below.  Yet after I load the game, every punch is named the same type, instead of the individual names I gave them.  Maybe you could just add Soldering Iron tools?

#### What You Expect to Happen

The tools to be named "Nickel Soldering Iron" or similar.

#### Script

https://pastebin.com/Cy2qss6p

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Artisan Worktables: 1.21.6
* Athenaeum: 0.3.8

**Comment by codetaylor** [comment]
Ok, so because of the way it works internally, combining the material name with the tool name, you only have to rename one of the tools with a single substitution marker and it will fill in the material names automatically and work for all tools.

```
<artisanworktables:artisans_punch_wood>.displayName = "Artisan's %s Soldering Iron";
```

The one line should be enough to rename *all* the punch tools.

And, yeah a soldering iron tool is on my radar: #127 

Also, there's a Discord if you're interested: http://discord.codetaylor.com

**Comment by Boolyman** [comment]
Thanks!
