### ISSUE TITLE
Artisan Integrations Crash on Startup

### ISSUE THREAD

**Issue by IcedReaper** [codetaylor/artisan-worktables#188]
#### Issue Description

AI crashes on startup.

#### What Happens

I'm trying to implement the Artisan Integrations mod into my modpack but sadly it crashes on startup. When I create a new test modpack with only JEI, Artisan Worktables, Athenaeum, and Artisan Integrations it works fine.
When I disable (rename to .disabled) AI in my modpack again the pack starts without a problem.

I readded the Botania Material Tools to the Configs of AW after the config refactoring earlier this week, but I don't think this would cause such a crash, but I don't know. Otherwise the Config of AW is untouched.

#### What You Expect to Happen

Start :D

#### Script

I only have Artisan Worktables CraftTweaker Scripts running, no AI scripts yet.

#### Crash Log

https://pastebin.com/wzZzduhH

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 4.1.19
* Artisan Worktables: 1.22.2
* Athenaeum: 1.17.4
* Artisan Integrations: 1.0.0

Thanks in advance,
IcedReaper

**Comment by codetaylor** [comment]
Hi, thanks for the report!

A Discord member mentioned that AI was crashing due to duplicate Botania tools in the AW configs. First, try removing the Botania tools from AW config:

![image](https://user-images.githubusercontent.com/1240716/65271551-40672680-dad2-11e9-8f74-b3cd0ad02894.png)

If that doesn't work, we'll go from there.

Also, you're welcome to join the Discord: http://discord.codetaylor.com

**Comment by IcedReaper** [comment]
Hi @codetaylor ,
thanks for the quick response.

I removed the custom botania tools and it works. :)

Thanks :)

**Comment by codetaylor** [comment]
You're welcome :)
