### ISSUE TITLE
Can't create an exact recipe with the exact GT tools

### ISSUE THREAD

**Issue by RCqaq** [codetaylor/artisan-worktables#205]
**Issue Description**
It seems that the Artisan couldn't resolve the exact gretech meta tools as a crafting tool and simply mixed all of them together. For example, a recipe requires hard hammer can be crafted even by a GT sword. And if you use the oredict of the tools such as <ore:craftingToolHardHammer>, it comes with the same problem.

**What Happens**
I created recipes that use gregtech tools as the crafting tools. Later I found all the "<gregtech:meta_tool>" things can be used in the recipe, such as when I am to craft a hopper with custom recipe, it ought to be only crafted by the hammer, but every meta tool no matter which meta it has can be used to craft the hopper.

**What You Expect to Happen**
The recipe should only be crafted when you use the exact tools.

 **Script**
https://paste.ubuntu.com/p/pYhvjTshfp/

**Affected Versions**
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- CraftTweaker: 4.1.19
- Artisan Worktables: 1.22.9
- Artisan Integrations: 1.0.0
- Athenaeum: 1.17.4
- GregTech CommunityEdition: 1.8.6.437
- CodeChickenLib: 3.2.3.358

**PS**: I am a Chinese and my English is not so good. If what I am saying confuses you, I'm sorry and I will try to explain the exact meaning I meant.

**Comment by codetaylor** [comment]
Thank you for the report!

When Artisan Worktables matches tools, it ignores the meta value because it was originally built with the assumption that all tools used in the tables would use metadata for damage and the damage should be ignored when matching. I'm surprised this hasn't been reported sooner.

The solution will require special handling of the GregTech tool when matching recipes, ideally using the tool handlers.
