### ISSUE TITLE
Add the ability to port already-existing recipes into certain worktables, possibly while adding a tool requirement

### ISSUE THREAD

**Issue by Lord-Felidae** [codetaylor/artisan-worktables#221]
The reason I think this could be a good idea is that some recipes use crafting to do more than simply turn some items into other items.

For example, Vanilla Food Pantry adds [multiple kinds of sandwiches](https://github.com/Wabbit0101/mods_hoardercraft/wiki/VFP-Sandwiches) that have different properties based on what ingredients are put into the crafting table, or multiple mods that use crafting recipes to link items or change item properties.

**Comment by codetaylor** [comment]
Thank you for the suggestion, however it is unlikely to be implemented due to both technical and time constraints.

This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects. I will keep this open in the backlog for now, but it is unlikely to be implemented.

**Comment by codetaylor** [comment]
This is likely not going to be possible without a significant rewrite of the internal recipe handling and I'm not sure how likely I am to do that.

The mod allows copying recipes at face value and turning them into recipes specific for the worktables without retaining a reference to the original recipe or calling any code on the original recipe. This prevents the mod from executing any special behavior that another mod's recipe might introduce.
