### ISSUE TITLE
Support JitPack builds

### ISSUE THREAD

**Issue by TagnumElite** [codetaylor/artisan-worktables#225]
I would appreciate it if your mod could be built and downloaded from jitpack.io
I am currently using CurseMaven for fetching dependencies.
I (and potentially others), would like to be able to use JitPack.

**Comment by codetaylor** [comment]
That's probably not going to happen.

**Comment by codetaylor** [comment]
I may have responded harshly, so for further clarification, this is my reasoning:

1. I would have to spend the time to determine why the builds are failing with Jitpack and potentially redesign my build process, modify my build scripts, and / or re-setup my development environment. I would rather spend my modding time working on the mods instead.
2. All tagged releases from the `master` branch are built same-day and uploaded to CurseForge. This means that the latest code available here will always be publicly available via CurseForge. If the code is a couple of commits ahead, it's usually due to document changes which are also auto-built immediately and updated on readthedocs.
3. CurseForge and FTB's CDN are the only two distribution sources that I have officially authorized to distribute my mods. I don't want to add another right now.

When it comes to modding, I usually use the following metrics to gauge whether or not I'm going to do work -- in no particular order:

* Is it a bug?
* Am I going to use it?
* Am I going to get joy from the process or result?
* Am I getting paid?
* Did I say I was going to do it?
* Is it going to benefit a large number of people?

I try not to be a complete jerk, however, and to that end, I'd be happy to hear any reasonable arguments you have that support the request. :)

**Comment by TagnumElite** [comment]
It's alright, I really just used the emoji to state that I acknowledge the respone.
Like I said, I don't mind using CurseMaven, just prefered JitPack.
I completely understand if you don't wish to spend the time debugging and testing JitPack.
