### ISSUE TITLE
I am willing to backport your mod..

### ISSUE THREAD

**Issue by SpaceXVI** [codetaylor/artisan-worktables#250]
I know that you don’t want issues that include backporting, but I really need to backport your mod to 1.7.10 (all ready backported taiga and modular machinery), I was just concerned about the license you put, does it mean I cannot do this? I really got mislead..

Thanks in advance.

**Comment by codetaylor** [comment]
Why do you *really need* to backport my mod?

My code is open-source because I want people to be able to:

1. easily view the source code in a readable state,
2. easily verify that the code isn't malicious, and
3. learn from the code.

My mods are licensed under a permissible, open-source license, Apache 2.0, because I want to make it easy for:

1. people to use snippets of my code in their projects, and
2. someone to pick up where I leave off if I stop modding or something bad happens to me.

I have a high standard of quality and a vision for my mods. I can't trust that you will adhere to the same standards of quality or the same vision that I do. I don't trust you to create an official port of any of my work because I have no idea who you are. Your GitHub account was created on May 3, 2020 and has no visible code that I can browse to assess the quality and competency of your work.

Any port of my mods that produces a product of less than ideal quality will dilute my brand and reflect poorly on the quality of my work.

I would prefer that you didn't port my mod, but I can't stop you as the license permits you to modify and distribute it. If you intend to move forward with the port, I ask that you please respect the terms of the license and if you distribute it or otherwise release it publicly, please include the word `Unofficial` in the title of the software. Additionally, I ask that you credit me where applicable and direct all support requests to your own channels.

https://www.apache.org/licenses/LICENSE-2.0

**Comment by SpaceXVI** [comment]
I understand that you might not trust me, but I promise to give the mod a really high quality, and keep track with the constant updates you're making, I am currently "almost" 25% done with the backport (well, I started doing the stuff like before yesterday but decided to ask you just to make sure I am not wasting my time)

If you're concerned about the progress I will make a repo soon, posting images of the current progress, following the license and doing as you wish.

when I release the backport you may test it yourself, if your vision sees it as poor or so I will try my best to improve it :fist_raised: 

Oh, by the way, reason being is that my pc is horrible, I can't really run 1.12.2 modpacks, and I really liked DDSS so I decided to do this..

**Comment by codetaylor** [comment]
> when I release the backport you may test it yourself

Thank you. Quite frankly, I don't have the time or the desire to perform an exhaustive, comprehensive test of AW's robust feature set that would satisfy me enough to endorse it. My project icons use a background that I designed to represent my particular brand and, as such, I would also appreciate it if you didn't use the official AW icon for your project. If you want to simply change the color of the icon's background, that would be sufficient. That being said, I bear you no ill will and wish you the best in your endeavor. :)

**Comment by SpaceXVI** [comment]
That really made me feel great, thank you so much, and yeah I was really confused about the icons, will try making another one, and again, don't worry about the "Unofficial" labels and stuff, I will make sure it's written and mentioned everywhere that this isn't official at all, and is 100% unofficial.

I would also like to point out that I am fully ready to take down the back-port anytime you want, because at the end of the day this is still your mod and your hard work!

I don't know the ETA for this, however, perhaps in a month or so, depending on my free time and other factors.
