### ISSUE TITLE
Can't put tools into tool slot in worktables

### ISSUE THREAD

**Issue by titantwoshot** [codetaylor/artisan-worktables#5]
Also i can't create recipe from for the table using CraftTweaker.

**Comment by codetaylor** [comment]
Tools won't go into the slot unless there is a recipe that uses the tool for the table. That behavior is intentional.

I need more information to help you with your CraftTweaker recipe:
* What version of the mod are you using?
* Where are you putting your CT scripts?
* Show me the CraftTweaker script you are using for the table.

**Comment by titantwoshot** [comment]
The Crafttweaker give this error message "ERROR: Error while applying actions"
Here is the recipe:
 "Worktable.addRecipeShapeless("tailor", <minecraft:string>, <ore:tailors_shears>, 5, [<betterwithaddons:wool:*>]);"

![image](https://user-images.githubusercontent.com/26327580/34466589-80885da6-ef0b-11e7-986b-a4b746c0ccf5.png)

Can't put tools into tool slot

**Comment by codetaylor** [comment]
Your recipe is not correct.

You are missing brackets `<>`.

`Worktable.addRecipeShapeless("tailor", <minecraft:string>, <ore:tailors_shears>, 5, [<betterwithaddons:wool:*>]);`

For reference on CraftTweaker usage:
* http://crafttweaker.readthedocs.io/en/latest/#
* https://github.com/codetaylor/artisan-worktables/blob/master/ZENSCRIPT.md
