### ISSUE TITLE
Add default recipes for the tables

### ISSUE THREAD

**Issue by CharCharthemonkey** [codetaylor/artisan-worktables#51]
is it possible to get a default set of recipes for the tables? just asking cause they show in JEI but dont have recipes and was simply wondering plz and ty

**Comment by codetaylor** [comment]
The mod is designed as a tool for mod pack makers. To that end, recipes are not provided for the tables and it is intended that you use CraftTweaker to provide your own recipes. Default recipes are provided for all the tools because there is a plethora of tools and it would be rather tedious to have to define recipes for all the tools. Recipes for the tools can be disabled if you want to provide your own. Since there are only a handful of tables, default recipes are not provided.

I may add recipes for the tables in the future, but it isn't a priority right now.

**Comment by CharCharthemonkey** [comment]
thank you bunches on answering both questions on the mortars one and this one

**Comment by Bulldog83** [comment]
It'll be good to add default recipes for tables. And without that need to rewrite many recipes for other items.

**Comment by codetaylor** [comment]
I have decided against adding default recipes for the tables. It is intended that you pick and choose which tables you want to use and create the recipes yourself to match the intended progression of your pack.
