### ISSUE TITLE
Multiple fluid options in recipes

### ISSUE THREAD

**Issue by TheOldOne822** [codetaylor/artisan-worktables#59]
I'd like to be able to make recipes accept more than one fluid, as an example I'd like to have the Blacksmith table use hot liquids (Lava and Blazing Pyrotheum) for tool and armor recipes with Blazing Pyrotheum requiring less.

Another thing is when using Liquid XP use either the Open Blocks or Thermal versions.

Yes I could just add 2 versions of the recipes and likely will for now but thought multiple fluid options in individual recipes would be a nice way to make it easier.

**Comment by codetaylor** [comment]
Yes, I agree that your suggestion would make it easier. That being said, I prefer to keep the API clean and unambiguous. To that end, I'm not going to introduce any functionality that will automatically create multiple recipes behind the scenes. It will be left to the user to create multiple versions of recipes if they so desire.

I suggest using CraftTweaker to define a function that will build and create multiple versions of the recipes for you. Here is a link to what I'm talking about: http://crafttweaker.readthedocs.io/en/latest/#AdvancedFunctions/Custom_Functions/

Regarding this:

> Another thing is when using Liquid XP use either the Open Blocks or Thermal versions.

If two mods register two different fluids, since there is currently no fluid dictionary, there isn't a convenient way to tell if the fluids should be treated as the same fluid short of building some kind of internal fluid dictionary or adding special cases for fluids. I can't possibly keep up with which mods add which fluids that should be treated as the same fluid. Again, I leave it to the user to define multiple recipes for each fluid.
