### ISSUE TITLE
Use the `bone` ore dictionary for bone tools

### ISSUE THREAD

**Issue by ChiriVulpes** [codetaylor/artisan-worktables#70]
My mod adds multiple bones which have the `bone` ore dictionary, and removes the vanilla bone. As a result, the bone tools are not craftable, since they don't use the `bone` ore dictionary.

**Comment by codetaylor** [comment]
I suggest also adding a `flint` oreDict entry and switching the flint tools to use that entry. Bone and flint tools are the only tools that don't use an oreDict entry as their primary ingredient. I think this would make it easier for pack makers to adjust the materials; they wouldn't have to redo 20 recipes per material.

**Comment by codetaylor** [comment]
Since Forge adds the vanilla bone item to the `bone` oreDict entry, it makes sense to switch the tool recipes to use the entry.

However, since Forge doesn't add a `flint` entry, I won't be adding the entry and changing the flint recipes to use it. I want the mod to make as few unnecessary additions as possible. I've added support for editing all the tool materials, including the primary recipe ingredient, in the latest alpha snapshot. If a pack developer wants to make a `flint` entry, it will be easy for them to pop into the json and edit the flint material.

The switch to the `bone` entry has been made and will be the default for bone tools in the next alpha snapshot.

**Comment by codetaylor** [comment]
Available in the alpha snapshot 1.12.2-1.15.25-10-gcce9f8f

Will be available in the beta 1.12.2-1.16.x
