### ISSUE TITLE
How About No Tools?

### ISSUE THREAD

**Issue by mayonnaisefarmer** [codetaylor/artisan-worktables#82]
With the recent sweeping change to tool ore dict entries being done for 1.16, is it possible that we'd get an option to simply set a recipe without a tool in your tables as well? I can't imagine it would see too much use, but I rather do enjoy the option since your tables have a really interesting property with how they function basically as Tinker's Tables + the toolbox being configured to hold any item.

It's a niche use for sure, but one I would definitely enjoy if at all possible. Something as simple as `addTool(null, 0)` or the like, but I'm not sure if it's actually as easy as letting us set a null tool since that doesn't work currently, or simply allow us to omit the `addTool` line if we'd like a recipe to not require a specific tool

As for an actual reason why this is something I would like, I'm using your mod as a "dual tier" type system, where making the tables themselves can function as a progress gate, and I don't think every recipe in them should require a tool for what I want to force people to use them for. Unfortunately, they require a tool at the moment which is no big deal but eh.

**Comment by BismuthBorealis** [comment]
This rather resembles #50.

**Comment by codetaylor** [comment]
I haven't really made this a priority for the following reasons:
1. the mod was originally created to perform crafts *with* tools;
2. because of (1), much of the code was written to assume at least one tool;
3. because of (2), it takes time to change;
4. because of (2), it's likely that something will break.

You're not the first person to want this, so I'll go ahead and add it to 1.16. :)

**Comment by codetaylor** [comment]
Available in alpha 1.12.2-1.15.25-21-g825ea34

Will be available in beta 1.12.2-1.16.x
